### PR TITLE
Use mvvm source generators

### PR DESCRIPTION
**Pull request by IvanDmitriev1**
Use MVVM source generators.

- [x] Update
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes

### CODE REVIEW

**Comment by pomianowski** [comment]
dotnet/wpf#6792
dotnet/wpf#6793

**Comment by IvanDmitriev1** [comment]
On my pc project builds.

**Comment by pomianowski** [comment]
> On my pc project builds.

Good old - "Weird, it works for me"

**Comment by IvanDmitriev1** [comment]
Perhaps this is due to the fact that I am using a preview version of visual studio.

**Comment by pomianowski** [comment]
Still in Known Issues
https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#issues-building-wpf-application-with-windows-desktop-607-and-608=

With workaround:
* To enable build in Windows Desktop 6.0.7, navigate to the directory containing the Microsoft.WinFx.targets file ( C:\Program Files\dotnet\sdk\6.0.302\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets )
* Add the following target in the file:
```xaml
<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
        <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
        <Analyzer Remove="@(Analyzer)" />
        <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
</Target>
```

**Comment by IvanDmitriev1** [comment]
Strange, with sdk 6.0.400-preview.22330.6, everything builds normally

**Comment by IvanDmitriev1** [comment]
I hope that the build errors will be fixed in sdk 6.0.400.

**Review by pomianowski — APPROVED** [review]

**Review by pomianowski — APPROVED** [review]

**Pull request closed without merging**
