### PR TITLE
`NavigationView` pane toggle button implementation 

### PR DESCRIPTION
**Pull request by IvanDmitriev1**
Implemented pane toggle button.
`TitleBar` now can be placed in logical order.
Added setting default values if the `TitleBar` property is set in `NavigationView`.

## Pull request type

- [ ] Update
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes

### CODE REVIEW

**Comment by pomianowski** [comment]
Hi, great job. The animation looks very elegant 😄 

However, there is a new bug with statically defined menu items. Take a look at the `NavigationViewPage` page
image

**Comment by IvanDmitriev1** [comment]
I didn't touch it, yesterday it worked. :(

**Comment by pomianowski** [comment]
And `AutoSuggestBox` margin breaks spacings for the top one
image

**Comment by IvanDmitriev1** [comment]
Should there be such icons ?
image

**Comment by pomianowski** [comment]
> Should there be such icons ? image


https://apps.microsoft.com/store/detail/winui-3-gallery/9P3JFPWWDZRC
image

**Comment by pomianowski** [comment]
Thanks for the suggestions and contributions. Looks fine to me at this stage

**Pull request merged**
