### PR TITLE
Fix Close Button icon color in TitleBar while mouse over

### PR DESCRIPTION
**Pull request by seasonyuu**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Update
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes

## What is the current behavior?

Normally, the TitleBar should change Close button background to Red, and change foreground to White while mouse over. But it looks like this now.

image

Issue Number: N/A

## What is the new behavior?

image

Because the `TitleBar.cs` hook mouse event, so the TemplateBinding in `TitleBar.xaml` cannot trigger by `IsMouseOver`. So this pull request continuely use the `Hover/RemoveHover` method in `TitleBarButton.cs` as event, and add a `MouseOverButtonsForeground` property to allow user defining this color.

-
-

### CODE REVIEW

**Comment by pomianowski** [comment]
hey @seasonyuu, thanks for your contribution to the project

**Comment by koal44** [comment]
This PR has some bugs that should be worked out.
1) Binding failures in TitleBar.xaml
```
<Setter Property="MouseOverButtonsForeground" Value="{Binding Path=MouseOverButtonsForeground, RelativeSource={RelativeSource AncestorType={x:Type controls:TitleBar}}}" />
```
There's no such property for `TitleBar` but there was one introduced for `TitleBarButton`. But anyhoo, the line can be omitted as the styling logic is entirely handled in code through `TitleBarButton.Hover()`

2) The `ButtonsForeground` is now broken when switching themes
To reproduce the bug: run the gallery app, hover over the TitleBar buttons (like minimize or close buttons), then switch themes and you'll see that the foreground is now stuck to the previous theme.
The reason for this is `ButtonsForeground = _cacheButtonsForeground`, which breaks the theme binding from
`<Setter Property="ButtonsForeground" Value="{DynamicResource ButtonForeground}" />`

**Comment by koal44** [comment]
image
as seen here, the buttons become invisible when switching to light theme

**Comment by seasonyuu** [comment]
Got it. Give me sometime

koal44 ***@***.***> 于 2024年3月17日周日 04:52写道：

**Pull request merged**
