### PR TITLE
Controls update

### PR DESCRIPTION
**Pull request by IvanDmitriev1**
Deleted `Dialog` control.
Changed .editorconfig so that it is the same as in the [dotnet/runtime repository.](https://github.com/dotnet/runtime/blob/main/.editorconfig)
Added folders for `TitleBar`, `MessageBox`, `ContentDialog`, `VirtualizingWrapPanel`, `NumberBox `controls.
Added small fixes.

## Pull request type

- [X] Update
- [ ] Bugfix
- [ ] Feature
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes

### CODE REVIEW

**Review by pomianowski — CHANGES_REQUESTED** [review]
Hey, thanks for organizing the cleanup.

For the namespace to work properly, **Properties\AssemblyInfo.cs** needs to be updated. Same for **VisualStudioToolsManifest.xml**.

As for `IDialogService`, I find it useful and think that it should be rewritten for `DialogControl`.

**Comment by IvanDmitriev1** [comment]
Ok.

**Comment by IvanDmitriev1** [comment]
> For the namespace to work properly, **Properties\AssemblyInfo.cs** needs to be updated. Same for **VisualStudioToolsManifest.xml**.

Actually I didn't change namespace, they all have the `Wpf.Ui.Controls` namespace.

**Comment by pomianowski** [comment]
> > For the namespace to work properly, **Properties\AssemblyInfo.cs** needs to be updated. Same for **VisualStudioToolsManifest.xml**.
> 
> Actually I didn't change namespace, they all have the `Wpf.Ui.Controls` namespace.

I'm not a fan of the solution when the namespace is not the same as the directory tree.

**Comment by IvanDmitriev1** [comment]
At the same time, all controls should have the namespace `Wpf.Ui.Controls`, isn't that right?

**Comment by pomianowski** [comment]
> At the same time, all controls should have the namespace `Wpf.Ui.Controls`, isn't that right?

No need, namespace is added to **AssemblyInfo**. 

https://github.com/lepoco/wpfui/blob/87f203ce2de3aacb2b15d8de6fd8c326bf7575d9/src/Wpf.Ui/Controls/Navigation/NavigationView.Parent.cs#L11
https://github.com/lepoco/wpfui/blob/87f203ce2de3aacb2b15d8de6fd8c326bf7575d9/src/Wpf.Ui/Properties/AssemblyInfo.cs#L20

**Comment by IvanDmitriev1** [comment]
> No need, namespace is added to **AssemblyInfo**.

But it for XAML not for c#.

**Comment by pomianowski** [comment]
> > No need, namespace is added to **AssemblyInfo**.
> 
> But it for XAML not for c#.

It doesn't matter what the namespace is, it could even be **Wpf.Ui.Xyz** and everything should still work

**Comment by IvanDmitriev1** [comment]
> Unless you mean a naming convention to keep everything neatly in one place. Well, so far I've decided that we should stick to the directory tree, but if everything in **Controls** is more convenient and in line with what is in the main WPF, we can consider it that way.

Yep

**Comment by pomianowski** [comment]
> > Unless you mean a naming convention to keep everything neatly in one place. Well, so far I've decided that we should stick to the directory tree, but if everything in **Controls** is more convenient and in line with what is in the main WPF, we can consider it that way.
> 
> Yep

Well, then, just like the main WPF, we can omit decorative subfolders and keep everything in one place, taking care of the correctness of the namespace.
https://github.com/dotnet/wpf/tree/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls

**Comment by IvanDmitriev1** [comment]
Then I prefer the directory tree.

**Comment by IvanDmitriev1** [comment]
But at the same time winui 3.
https://github.com/microsoft/microsoft-ui-xaml/tree/main/dev

**Comment by pomianowski** [comment]
> 

Well yes, but it's a CPP project

**Comment by IvanDmitriev1** [comment]
In my opinion , c++ namespace structured by folders, at least I did.

**Review by pomianowski — APPROVED** [review]

**Pull request merged**
