### PR TITLE
Fix titlebar color when using backdrop in WPF `Window`

### PR DESCRIPTION
**Pull request by pomianowski**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Update
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes

## What is the current behavior?

Window can have a color in custom titlebar when **Show accent colors** option is enabled in Windows.

Issue Number: N/A

## What is the new behavior?

After enabling Mica backdrop, the titlebar color should be removed.

### CODE REVIEW

**Comment by pomianowski** [comment]
FYI: @Jay-o-Way, @aquinn39
rel.: https://github.com/microsoft/PowerToys/issues/30206

**Comment by jaimecbernardo** [comment]
@pomianowski  Awesome work here :)
I've added this fix to https://github.com/microsoft/PowerToys/pull/33458 , while 4.0.0 is not released.
Thank you!

Quick question: Why `uint titlebarPvAttribute = 0xFFFFFFFE;` and not `uint titlebarPvAttribute = 0xFFFFFFFF;` ?

**Comment by aquinn39** [comment]
> @pomianowski  Awesome work here :)
> 
> I've added this fix to https://github.com/microsoft/PowerToys/pull/33458 , while 4.0.0 is not released.
> 
> Thank you!
> 
> 
> 
> Quick question: Why `uint titlebarPvAttribute = 0xFFFFFFFE;` and not `uint titlebarPvAttribute = 0xFFFFFFFF;` ? 

I got the value from DWMWA_BORDER_COLOR [here](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute). This value appearantly hides the window border, so I thought maybe it might work for the title bar as well, which it did. 0xFFFFFFFF (DWMWA_COLOR_DEFAULT) just resets the title bar colour to the default system behaviour, which means using the accent colour if you have that option enabled - that behaviour actually is documented under DWMWA_CAPTION_COLOR.

Makes me wonder if DWMWA_COLOR_NONE (0xFFFFFFFE) also works on DWMWA_TEXT_COLOR to hide the caption text (not that it's necessary in this case).

**Comment by aquinn39** [comment]
Interestingly this behaviour is actually correctly documented in dwmapi.h.
image

**Pull request merged**
